[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.0"


[workspace]
members = ["programs/cp-swap"]

[features]
seeds = false
skip-lint = false

[programs.Localnet]
raydium_cp_swap = "CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C"


[registry]
url = "https://github.com/raydium-io/raydium-cp-swap"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://testnet.dev2.eclipsenetwork.xyz"

[[test.validator.clone]]
address = "HtPorWESXkST2NLsq7CkjvGSeF4JhvXFvtE8S7MtKeXZ"

[[test.validator.clone]]
address = "7BzPBrKgrExxLVYnpzyjQ2soWwBMEoLGBnT4achZNq4u"
